name: MarkdownChecker

on:
  #DO NOT CHANGE
  workflow_dispatch: ## Manual run possible
  push:
    branches: [ master , main ]
    paths:
    - "docs/**" #all docs

jobs:
  markdown-link-check:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
    - uses: actions/checkout@master
    - name: markdownlint-cli
      uses: nosborn/github-action-markdown-cli@v1.1.1
      with:
        files: "*.md"
